image: samueldebruyn/debian-git

pipelines:
  default:
    - step:
        name: Deploy to secretsanta production
        deployment: production
        script:
          - apt-get update
          - apt-get -qq install git-ftp
          - git ftp push -v --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://$FTP_HOST
