steps:
- name: node:18.13.0
  entrypoint: npm
  args: ["install"]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      sed -i "s|##_MONGOURI##|${_MONGOURI}|g" app.yaml
      gcloud app deploy
timeout: 1800s
substitutions:
  _MONGOURI: ${_MONGOURI}