version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./private/data:/var/lib/mongo
    ports:
      - "27017:27017"

  minio:
    image: bitnami/minio
    restart: always
    environment:
      MINIO_ROOT_USER: rootroot
      MINIO_ROOT_PASSWORD: rootroot
    ports:
      - "9000:9000"
      - "9001:9001"