version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${mongodbUsername}
      MONGO_INITDB_ROOT_PASSWORD: ${mongodbPassword}
    volumes:
      - ./private/mongodb/data:/data/db
    ports:
      - '27017:27017'

  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${minioAccessKey}
      MINIO_ROOT_PASSWORD: ${minioSecretKey}
    command: 'server /data --console-address ":9001"'
    volumes:
      - ./private/minio/data:/data
    ports:
      - '9000:${minioPort}'
      - '9001:9001'
  
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:${minioPort} ${minioAccessKey} ${minioSecretKey};
      /usr/bin/mc mb myminio/${minioBucket};
      /usr/bin/mc anonymous set download myminio/${minioBucket};
      exit 0;
      "