name: Run linter

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16

      - working-directory: .
        run: npm install
      - working-directory: .
        run: npm run lint